/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParallelEarthRouteImport } from './routes/parallel-earth'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GhostTwinRouteImport } from './routes/ghost-twin'
import { Route as IndexRouteImport } from './routes/index'

const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallelEarthRoute = ParallelEarthRouteImport.update({
  id: '/parallel-earth',
  path: '/parallel-earth',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostTwinRoute = GhostTwinRouteImport.update({
  id: '/ghost-twin',
  path: '/ghost-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ghost-twin': typeof GhostTwinRoute
  '/insights': typeof InsightsRoute
  '/parallel-earth': typeof ParallelEarthRoute
  '/profile': typeof ProfileRoute
  '/replay': typeof ReplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ghost-twin': typeof GhostTwinRoute
  '/insights': typeof InsightsRoute
  '/parallel-earth': typeof ParallelEarthRoute
  '/profile': typeof ProfileRoute
  '/replay': typeof ReplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ghost-twin': typeof GhostTwinRoute
  '/insights': typeof InsightsRoute
  '/parallel-earth': typeof ParallelEarthRoute
  '/profile': typeof ProfileRoute
  '/replay': typeof ReplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ghost-twin'
    | '/insights'
    | '/parallel-earth'
    | '/profile'
    | '/replay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ghost-twin'
    | '/insights'
    | '/parallel-earth'
    | '/profile'
    | '/replay'
  id:
    | '__root__'
    | '/'
    | '/ghost-twin'
    | '/insights'
    | '/parallel-earth'
    | '/profile'
    | '/replay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GhostTwinRoute: typeof GhostTwinRoute
  InsightsRoute: typeof InsightsRoute
  ParallelEarthRoute: typeof ParallelEarthRoute
  ProfileRoute: typeof ProfileRoute
  ReplayRoute: typeof ReplayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel-earth': {
      id: '/parallel-earth'
      path: '/parallel-earth'
      fullPath: '/parallel-earth'
      preLoaderRoute: typeof ParallelEarthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghost-twin': {
      id: '/ghost-twin'
      path: '/ghost-twin'
      fullPath: '/ghost-twin'
      preLoaderRoute: typeof GhostTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GhostTwinRoute: GhostTwinRoute,
  InsightsRoute: InsightsRoute,
  ParallelEarthRoute: ParallelEarthRoute,
  ProfileRoute: ProfileRoute,
  ReplayRoute: ReplayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
